### ISSUE TITLE
Invalid MEX-file

### ISSUE THREAD

**Issue by zyzhong** [rbgirshick/rcnn#13]
After running key = caffe('get_init_key'), problem like this:
Invalid MEX-file '/path/to/rcnn/external/caffe/matlab/caffe/caffe.mexa64': libcudart.so.6.0: cannot open shared object file: No such file or directory

but i already add /usr/local/cuda-6.0/lib64 to LD_LIBRARY_PATH.
Why this issue still happen? BTW, I use the newest version caffe, and the "make runtest" of caffe passed.

**Comment by Tgaaly** [comment]
matlab must be open from the terminal or else it doesnt take the paths

from the terminal:
```
cd /usr/local/MATLAB/<your version of matlab>/bin
./matlab
```

**Comment by mgarbade** [comment]
Starting matlab from terminal helped me. Thanks!

**Comment by wuhuo714** [comment]
@ddetone  It works,thanks!

**Comment by xzy295461445** [comment]
I have the same problem, but i make the caffe cpu only. How to solve this?
