### ISSUE TITLE
Matlab internal problem after running 'rcnn_exp_cache_features('train')'

### ISSUE THREAD

**Issue by czhsuccess** [rbgirshick/rcnn#20]
I was trying to extract features from PASCAL VOC 2007 datasets according to the tutorial, everything is normal until matlab throwed a System Error: 'MATLAB has encountered an internal problem and needs to close'. I use ubuntu 14.04 and the matlab edition is 2013a. The R-CNN is runned in CPU mode.

The error was thrown while excuting line 36: 'rcnn_model.cnn.layers = caffe('get_weights')' in rcnn_load_model.m:

Some details of the error: 
## MATLAB crash file:/root/matlab_crash_dump.4529-1:

```
        Abort signal detected at Wed Aug 27 18:56:28 2014
```

---

Configuration:
  Crash Decoding     : Disabled
  Current Visual     : 0x23 (class 4, depth 24)
  Default Encoding   : UTF-8
  GNU C Library      : 2.19 stable
  MATLAB Architecture: glnxa64
  MATLAB Root        : /usr/local/MATLAB/R2013a
  MATLAB Version     : 8.1.0.604 (R2013a)
  Operating System   : Linux 3.13.0-34-generic #60-Ubuntu SMP Wed Aug 13 15:45:27 UTC 2014 x86_64
  Processor ID       : x86 Family 6 Model 58 Stepping 9, GenuineIntel
  Virtual Machine    : Java 1.6.0_17-b04 with Sun Microsystems Inc. Java HotSpot(TM) 64-Bit Server VM mixed mode
  Window System      : The X.Org Foundation (11501000), display :0

Fault Count: 1

Abnormal termination:
Abort signal

Register State (from fault):
  RAX = 0000000000000000  RBX = 00007ff6f1389660
  RCX = ffffffffffffffff  RDX = 0000000000000006
  RSP = 00007ff7e7a7f788  RBP = 00007ff6f1389660
  RSI = 00000000000011e4  RDI = 00000000000011b1

   R8 = 0000000000000000   R9 = 0000000000000000
  R10 = 0000000000000008  R11 = 0000000000000206
  R12 = 00007ff6f13896c0  R13 = 00007ff6f1389980
  R14 = 00007ff7e7a7faa0  R15 = 000000000000003c

  RIP = 00007ff7f95d9f89  EFL = 0000000000000206

   CS = 0033   FS = 0000   GS = 0000

Stack Trace (from fault):
[  0] 0x00007ff7f95d9f89                    /lib/x86_64-linux-gnu/libc.so.6+00225161 gsignal+00000057
[  1] 0x00007ff7f95dd398                    /lib/x86_64-linux-gnu/libc.so.6+00238488 abort+00000328
[  2] 0x00007ff6f11753b9                        /usr/local/lib/libglog.so.0+00041913
[  3] 0x00007ff6f11769fd                        /usr/local/lib/libglog.so.0+00047613
[  4] 0x00007ff6f117889d                        /usr/local/lib/libglog.so.0+00055453 _ZN6google10LogMessage9SendToLogEv+00000589
[  5] 0x00007ff6f11765ec                        /usr/local/lib/libglog.so.0+00046572 _ZN6google10LogMessage5FlushEv+00000156
[  6] 0x00007ff6f11791be                        /usr/local/lib/libglog.so.0+00057790 _ZN6google15LogMessageFatalD2Ev+00000014
[  7] 0x00007ff6f14267f0 /rcnn/rcnn/external/caffe/matlab/caffe/caffe.mexa64+00575472
[  8] 0x00007ff6f140bdf2 /rcnn/rcnn/external/caffe/matlab/caffe/caffe.mexa64+00466418
[  9] 0x00007ff6f13b6af9 /rcnn/rcnn/external/caffe/matlab/caffe/caffe.mexa64+00117497
[ 10] 0x00007ff6f13b61c3 /rcnn/rcnn/external/caffe/matlab/caffe/caffe.mexa64+00115139 mexFunction+00000203
[ 11] 0x00007ff7f1c3cf8a     /usr/local/MATLAB/R2013a/bin/glnxa64/libmex.so+00110474 mexRunMexFile+00000090
[ 12] 0x00007ff7f1c390f9     /usr/local/MATLAB/R2013a/bin/glnxa64/libmex.so+00094457
[ 13] 0x00007ff7f1c39f1c     /usr/local/MATLAB/R2013a/bin/glnxa64/libmex.so+00098076
[ 14] 0x00007ff7fb56b6b2 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_dispatcher.so+00562866 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00000594
[ 15] 0x00007ff7faff5bf6 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+04262902
[ 16] 0x00007ff7faff637a /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+04264826
[ 17] 0x00007ff7faff6eea /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+04267754
[ 18] 0x00007ff7fae59bbd /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+02575293
[ 19] 0x00007ff7fae85412 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+02753554
[ 20] 0x00007ff7fae8553f /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+02753855
[ 21] 0x00007ff7fafa2500 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+03921152
[ 22] 0x00007ff7fadbe8ac /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+01939628
[ 23] 0x00007ff7fadba993 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+01923475
[ 24] 0x00007ff7fadbb797 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+01927063
[ 25] 0x00007ff7fae26e50 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+02367056
[ 26] 0x00007ff7fb56b6b2 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_dispatcher.so+00562866 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00000594
[ 27] 0x00007ff7fae09256 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+02245206
[ 28] 0x00007ff7fadb9a86 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+01919622
[ 29] 0x00007ff7fadbe374 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+01938292
[ 30] 0x00007ff7fadba993 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+01923475
[ 31] 0x00007ff7fadbb797 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+01927063
[ 32] 0x00007ff7fae26e50 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+02367056
[ 33] 0x00007ff7fb56b6b2 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_dispatcher.so+00562866 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00000594
[ 34] 0x00007ff7fae09256 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+02245206
[ 35] 0x00007ff7fadb9a86 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+01919622
[ 36] 0x00007ff7fadbe374 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+01938292
[ 37] 0x00007ff7fadba993 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+01923475
[ 38] 0x00007ff7fadbb797 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+01927063
[ 39] 0x00007ff7fae26e50 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+02367056
[ 40] 0x00007ff7fb56b6b2 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_dispatcher.so+00562866 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00000594
[ 41] 0x00007ff7fae09256 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+02245206
[ 42] 0x00007ff7fad9509d /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+01769629
[ 43] 0x00007ff7fadbdb0e /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+01936142
[ 44] 0x00007ff7fadba993 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+01923475
[ 45] 0x00007ff7fadbb797 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+01927063
[ 46] 0x00007ff7fae26e50 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+02367056
[ 47] 0x00007ff7fb56b6b2 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_dispatcher.so+00562866 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00000594
[ 48] 0x00007ff7fadf5dcb /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+02166219
[ 49] 0x00007ff7fadb37cc /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+01894348
[ 50] 0x00007ff7fadafe1d /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+01879581
[ 51] 0x00007ff7fadb0255 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwm_interpreter.so+01880661
[ 52] 0x00007ff7f1e65fae /usr/local/MATLAB/R2013a/bin/glnxa64/libmwbridge.so+00139182
[ 53] 0x00007ff7f1e66111 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwbridge.so+00139537
[ 54] 0x00007ff7f1e66ce5 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwbridge.so+00142565 _Z8mnParserv+00000725
[ 55] 0x00007ff7fb8033d2   /usr/local/MATLAB/R2013a/bin/glnxa64/libmwmcr.so+00447442 _ZN11mcrInstance30mnParser_on_interpreter_threadEv+00000034
[ 56] 0x00007ff7fb7e29ac   /usr/local/MATLAB/R2013a/bin/glnxa64/libmwmcr.so+00313772
[ 57] 0x00007ff7fb7e2b88   /usr/local/MATLAB/R2013a/bin/glnxa64/libmwmcr.so+00314248
[ 58] 0x00007ff7ef37a5c6   /usr/local/MATLAB/R2013a/bin/glnxa64/libmwuix.so+00480710
[ 59] 0x00007ff7ef387df2   /usr/local/MATLAB/R2013a/bin/glnxa64/libmwuix.so+00536050
[ 60] 0x00007ff7fbecd862 /usr/local/MATLAB/R2013a/bin/glnxa64/libmwservices.so+01845346
[ 61] 0x00007ff7fbece50f /usr/local/MATLAB/R2013a/bin/glnxa64/libmwservices.so+01848591 _Z25svWS_ProcessPendingEventsiib+00001615
[ 62] 0x00007ff7fb7e35ef   /usr/local/MATLAB/R2013a/bin/glnxa64/libmwmcr.so+00316911
[ 63] 0x00007ff7fb7e3f5c   /usr/local/MATLAB/R2013a/bin/glnxa64/libmwmcr.so+00319324
[ 64] 0x00007ff7fb7dd592   /usr/local/MATLAB/R2013a/bin/glnxa64/libmwmcr.so+00292242
[ 65] 0x00007ff7f9971182              /lib/x86_64-linux-gnu/libpthread.so.0+00033154
[ 66] 0x00007ff7f969e38d                    /lib/x86_64-linux-gnu/libc.so.6+01029005 clone+00000109

This error was detected while a MEX-file was running. If the MEX-file
is not an official MathWorks function, please examine its source code
for errors. Please consult the External Interfaces Guide for information
on debugging MEX-files.

If this problem is reproducible, please submit a Service Request via:
    http://www.mathworks.com/support/contact_us/

A technical support engineer might contact you with further information.

Thank you for your help.

Anyone can tell me how I should solve the problem?

**Comment by jensen810814** [comment]
same problem.....can anyone tell me how to solve it? plz..

**Comment by TorosFanny** [comment]
same problem

**Comment by ideal** [comment]
Have this been fixed?

**Comment by SergeyChesalov** [comment]
Try it [https://www.mathworks.com/support/bugreports/1297894](url)

**Comment by JunjieHu** [comment]
I have the same problem. Any solution?

**Comment by SergeyChesalov** [comment]
JunjieHu, You need to register on the site and follow the requirements
