### ISSUE TITLE
Problem with " Training R-CNN models and testing "

### ISSUE THREAD

**Issue by Michael-Kyriacou** [rbgirshick/rcnn#22]
Hello, 
i've managed to install everything ok on my computer, including caffe and all its dependecies and running the rcnn_demo just fine.
Now am stuck here: 

     "Now to run the training and testing code, use the following experiments script:
            >> test_results = rcnn_exp_train_and_test()

where i get the following error:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Training options:
          bias_mult: 10
         cache_name: 'v1_finetune_voc_2007_trainval_iter_70k'
         checkpoint: 0
          crop_mode: 'warp'
       crop_padding: 16
               imdb: [1x1 struct]
            k_folds: 0
              layer: 7
           net_file: './data/caffe_nets/finetune_voc_2007_trainval_iter_70k'
    pos_loss_weight: 2
              svm_C: 1.0000e-03
       net_def_file: './model-defs/rcnn_batch_256_output_fc7.prototxt'

feature stats: 1/200
Error using  * 
Inner matrix dimensions must agree.
Error in rcnn_pool5_to_fcX (line 21)
    feat = max(0, bsxfun(@plus, feat*rcnn_model.cnn.layers(i).weights{1}, ...

Error in rcnn_feature_stats (line 39)
    X = rcnn_pool5_to_fcX(X, layer, rcnn_model);

Error in rcnn_train (line 78)
opts.feat_norm_mean = rcnn_feature_stats(imdb, opts.layer, rcnn_model);

Error in rcnn_exp_train_and_test (line 19)
[rcnn_model, rcnn_k_fold_model] = ...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

IMPORTANT NOTES:
To extract the features, i've changed the value of " input_dim: " from "256" to "50" inside the file ./model-defs/rcnn_batch_256_output_pool5.prototxt so i can prevent matlab from crashing . I don't have a really powerfull GPU (NVIDIA GT 540M ), so i thought maybe that was the problem. I've changed the value from "256" to "50"(it was a  random number i choice) because i've read in another forum that it will help and ineed it i managed to make it work around this time and finish all of 4 commands below without any errors or crashing of matlab this time 

>> rcnn_exp_cache_features('train');   % chunk1
>> rcnn_exp_cache_features('val');     % chunk2
>> rcnn_exp_cache_features('test_1');  % chunk3
>> rcnn_exp_cache_features('test_2');  % chunk4

Now am not sure what i really changed there and whether that was important. Please some help by anyone who knows what is wrong with my case will be appreciated. 

Thank you.

**Comment by Kyung-Min** [comment]
Did you notice any warning? during the computation?

**Comment by Michael-Kyriacou** [comment]
Hello, I've managed to run the command on another Computer with a more powerful Graphical Card, NVidia Tesla K40. I guess my problem was the insufficient memory on my laptop and i needed a more powerful pc . Thanks for the answer and the consideration. In overall, everything works ok

**Comment by blackCmd** [comment]
@Michael-Kyriacou  & @Kyung-Min 
Hi i've used labtop so i can't use GPU.
In my case, matlab crash is occured after "test_results = rcnn_exp_train_and_test()" function....

When i run "rcnn_demo" on matlab, crash was occured too. So, i tried "rcnn_demo('PASCAL',0)" not "rcnn_demo" then crash wasn't occured.

So i think "test_results = rcnn_exp_train_and_test()" function use gpu..
How can i use the function on cpu mode? or is there anyone who tell me solution?

pls......

**Comment by mahatmawoo** [comment]
Hi @blackCmd, try checking under rcnn_config.m, set line 45 to USE_GPU= false;
