### ISSUE TITLE
How to get selective_search_data for My own data-set ? 

### ISSUE THREAD

**Issue by CharlesShang** [rbgirshick/rcnn#25]
Hi, Ross and everyone
I'm training a new RCNN model on my own data-set. I notice "./data/selective_search_data/" contains some pre-generated selective-search(ss) data. If I didn't miss anything in the code, "selective_search_boxes.m" seems to be used to generate the ss results.
Is there any other inner tricks to generate these ss data?  
Charles,
Regards,

**Comment by aldenezy** [comment]
Hi CharlesShang, 

Did you ever figure out how to get selective search data for your dataset?

**Comment by rbgirshick** [comment]
My recommendation is to the look at the provided demo. It computes
selective search boxes on an example image. You can generalize that code to
compute selective search boxes on your dataset. See:
https://github.com/rbgirshick/rcnn/blob/master/selective_search/selective_search_boxes.m
.

Ross

**Comment by CharlesShang** [comment]
I've fine-tuned your model on my dataset. It run very well. 
Thx

**Comment by wuxinhong** [comment]
@CharlesShang  Can you tell me how you make it?

**Comment by Kongsea** [comment]
@CharlesShang Could you please share your code to obtain selective_search_data for other dataset? Thank you.
