### ISSUE TITLE
rcnn_build() error: anigauss_mex.c  not a normal file or does not exist

### ISSUE THREAD

**Issue by phoenixbai** [rbgirshick/rcnn#30]
Hi,

Not sure if this is the right place for asking a question, if not, please direct me to the right place.

I am trying to build rcnn and by following the instructions, I did rcnn_build() and it throws warnings & errors below:

```
>> rcnn_build()
Compiling the anisotropic gauss filtering of:
   J. Geusebroek, A. Smeulders, and J. van de Weijer
   Fast anisotropic gauss filtering
   IEEE Transactions on Image Processing, 2003
Source code/Project page:
   http://staff.science.uva.nl/~mark/downloads.html#anigauss


Warning: You are using gcc version "4.8.2".  The version
         currently supported with MEX is "4.7.x".
         For a list of currently supported compilers see: 
         http://www.mathworks.com/support/compilers/current_release/


    mex:  selective_search/SelectiveSearchCodeIJCV/Dependencies/anigaussm/anigauss_mex.c  not a normal file or does not exist.

Unable to complete successfully.

Error in rcnn_build (line 13)
    mex -outdir bin ...

>> 
```

What goes wrong here? it is the gcc version?
how could I solve it? my caffe configuration is definitely right, so it should`t be related to that.
any enlightenment would be highly appreciated.

Thank you!

**Comment by aamirshaikh86** [comment]
hey how to add manually

**Comment by NerminSalem** [comment]
@aamirshaikh86 you will find the link to downloaded manually in rcnn/selective_search/fetch_selective_search.sh
make sure to put the downloaded folder in rcnn/selective_search
