### ISSUE TITLE
Unable to run fine-tuning code on pascal voc 2007

### ISSUE THREAD

**Issue by aryanrajveersingh** [rbgirshick/rcnn#33]
Hi,

I am trying to train voc_2007 data as per the example in readme. I created the make window file and executed the following fine-tuning code 

GLOG_logtostderr=1 ../../build/tools/finetune_net.bin pascal_finetune_solver.prototxt /home/rajee/rcnn-master/data/caffe_nets/ilsvrc_2012_train_iter_310k 2>&1 | tee log.txt

but i am getting the following error - 
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0129 11:33:52.821279  4667 finetune_net.cpp:4] Deprecated. Use caffe train --solver=... [--weights=...] instead.

Can you please help me with this.

Thanks in advance.

**Comment by bbliao** [comment]
I have the same problem before, and I have solved it by using the following code:

GLOG_logtostderr=1 ../../build/tools/caffe.bin train \
-solver pascal_finetune_solver.prototxt \
-weights /your path/data/caffe_nets/ilsvrc_2012_train_iter_310k \
2>&1 | tee log.txt

;)

**Comment by aryanrajveersingh** [comment]
Thanks a lot bbliao :) That worked.
