### ISSUE TITLE
MATLAB crash

### ISSUE THREAD

**Issue by mitbal** [rbgirshick/rcnn#35]
My matlab crash (segmentation fault) when I call it from rcnn folder.
It looks like the problem is because I haven't included /opt/intel/mkl/lib/intel64 into LD_LIBRARY_PATH.
However, my caffe installation is using openblas. Is there a way to run rcnn using this library?

I am using the latest stable release of caffe, Matlab 2013a, and Ubuntu 14.04.

Thanks.

**Comment by blackCmd** [comment]
i have same error... ㅠㅠ i have reinstalled ubuntu 5times... ㅠㅠ
Did you solve the error?
Would you tell me how can fix please ...

**Comment by blackCmd** [comment]
Wow!!!! i got it !!!!!!
