### ISSUE TITLE
When run rcnn_demo, MATLAB gives: Error using caffe Expected 3 arguments, got 2

### ISSUE THREAD

**Issue by ChenSiqin** [rbgirshick/rcnn#36]
Hello everyone,
 
I used the up-to-date CAFFE and got the R-CNN source code by cloning the repository: git clone https://github.com/rbgirshick/rcnn.git. I successfully finished the RCNN startup, rcnn_build() and got the key -2 after running key = caffe(‘get_init_key’). But when I run the rcnn_demo, I got the ERROR in MATLAB:
~~~~~~~~~~~~~~~~~~~
Welcome to the PASCAL demo
Running in GPU mode
(To run in CPU mode, call rcnn_demo(demo_choice, 0) instead)
Press any key to continue
Initializing R-CNN model (this might take a little while)
Error using caffe
Expected 3 arguments, got 2

Error in rcnn_load_model (line 27)
rcnn_model.cnn.init_key = ...

Error in rcnn_demo (line 59)
rcnn_model = rcnn_load_model(rcnn_model_file, use_gpu);

Need your help. THANKS！

Best,
siqin

**Comment by lolongcovas** [comment]
the new version of CAFFE, to initialize caffe you need 3 parameters: prototext def, model name and a string to indicate"test" or "train".

best

**Comment by ChenSiqin** [comment]
I find rcnn_model.cnn.init_key = ...
    caffe('train', rcnn_model.cnn.definition_file, rcnn_model.cnn.binary_file);  in rcnn_load_model function. Do I change the the parameters there ?  Could you tell me more specifically ? Thanks you very much!

**Comment by ChenSiqin** [comment]
I  add another parameter 'train' or 'test' to rcnn_model.cnn.init_key = ...
caffe('train', rcnn_model.cnn.definition_file, rcnn_model.cnn.binary_file). 
I  met the ERROR:
Error using caffe
Unknown command 'set_phase_test'

Error in rcnn_load_model (line 34)
caffe('set_phase_test');
So I commet the 'caffe('set_phase_test')' and I succeeded. And is that right ? Thank you very much!

**Comment by lolongcovas** [comment]
caffe("init", prototext def filename, model filename, "test") for forward pass

**Comment by Coldmooon** [comment]
Solved my probem~

**Comment by hongzhenwang** [comment]
how solved?

**Comment by xksteven** [comment]
It's solved because either you should use the Caffe 0.99 that's been provided and Matlab 2012 or you modify the file rcnn_load_model to change the caffe call to caffe("init", prototext def filename, model filename, "test") and comment out the set phase test portion.

**Comment by Elpidam** [comment]
@xksteven  "caffe("init", prototext def filename, model filename, "test") and comment out the set phase test portion" using caffe master (0.9999 version) and Matlab 2014a?

**Comment by Elpidam** [comment]
I still get the message


-----------------------------------------------------------
Undefined function 'caffe' for input arguments of type 'char'.

Error in rcnn_load_model (line 27)
rcnn_model.cnn.init_key = caffe('init', rcnn_model.cnn.definition_file,
rcnn_model.cnn.binary_file,'test');
-----------------------------------------------------------

**Comment by Elpidam** [comment]
@lolongcovas hello... can you indicate to me the path to find the caffe_ in order to realize how to set the arguments? 
____________________________
Error using caffe_
Usage: caffe_(api_command, arg1, arg2, ...)
________________________________

**Comment by Elpidam** [comment]
The only solution is to follow the instructions and implement the method using Caffe-0.999 and Matlab R2012b

**Comment by Elpidam** [comment]
Where caffe.cpp is located in caffe-0.999?

**Comment by neouyghur** [comment]
replace `caffe("init", prototext def filename, model filename)` with  `caffe.Net(rcnn_model.cnn.definition_file, rcnn_model.cnn.binary_file, 'test');`

**Comment by rimphyd** [comment]
@neouyghur 
It doesnt work either:
Undefined variable "caffe" or class "caffe.Net".

Hi guys, I dont have Matlab 2012b. My lab only have 2014a. Is there any solution to this?

I dont know if this would work, but would someone willing to share the file caffe.mexa64 built for 2012b.
My Linux(64bit) gcc/g++ version is (Ubuntu/Linaro 4.7.3-12ubuntu1) 4.7.3

Thank you in advance.

**Comment by Aky97567** [comment]
Hi,
Here is the caffe.mexa64 for caffe-0.999. If you need the one for newer
versions of caffe, let me know. I am not an expert and i dont know how this
works. But i could find this file so you can have it.

**Comment by rimphyd** [comment]
Aky97567, I'm sorry do you have that file ?
