### ISSUE TITLE
Check/update R-CNN for Caffe v0.999

### ISSUE THREAD

**Issue by shelhamer** [rbgirshick/rcnn#4]
[Caffe v0.999](https://github.com/BVLC/caffe/releases/tag/v0.999) introduced a fair number of changes, so I suspect R-CNN might need a few adjustments. We can update the vetted R-CNN release once it's ready!

**Comment by Elpidam** [comment]
Hello! I noticed before some changes in r-cnn code in order to be compatible with Matlabr2014a. May you indicate to me the #issue to find it ? Thank u in advance!

**Comment by Elpidam** [comment]
Dear @rbgirshick  I've tried to finetune net on my own dataset but it seems there are some incompatibilities with caffe 0.999. Finetune.net is not placed anywhere and when I tried to finetune the network with  caffe train --solver= mysolver.prototxt -weights _iter_5000.caffemodel, i could find executable caffe. May you suggest some other way to solve this issue. I have already make windows files for my dataset.
