### ISSUE TITLE
PASCAL VOC 2007 Dataset

### ISSUE THREAD

**Issue by bluemellophone** [rbgirshick/rcnn#48]
I've been trying to get this implementation online, but am running into a roadblock with the PASCAL 2007 dataset.  It appears as though pascallin.ecs.soton.ac.uk is down and unreachable.

Does anybody have a working mirror or willing to host a copy of the data:
- http://pascallin.ecs.soton.ac.uk/challenges/VOC/voc2007/VOCtrainval_06-Nov-2007.tar
- http://pascallin.ecs.soton.ac.uk/challenges/VOC/voc2007/VOCtest_06-Nov-2007.tar
- http://pascallin.ecs.soton.ac.uk/challenges/VOC/voc2007/VOCdevkit_08-Jun-2007.tar

Edit: If I can get a copy of the data, I will add it to the academictorrents.com tracker so this doesn't happen again.

Edit 2: I'm still trying to track them all down, but I've added some of the missing VOC dataset files to academictorrents.com: http://academictorrents.com/browse.php?search=voc

**Comment by BinRoot** [comment]
Confirmed. I'm having the same issue.

**Comment by zuacubd** [comment]
Why I cannot download from the academic torrents.com ?

**Comment by bluemellophone** [comment]
@zuacubd I just checked the torrents and, while a little slow, they are all working.  I did notice that the magnet took a really long time to resolve from academictorrents.com, but I just opted to use the actual torrent files themselves.

**Comment by xksteven** [comment]
There's also this link from university of Texas. One can use wget to download the dataset.

http://vision.cs.utexas.edu/voc/

**Comment by JoeHowse** [comment]
There is also a mirror of the entire VOC2007 website: http://host.robots.ox.ac.uk/pascal/VOC/voc2007.  It is hosted by the Robotics Research Group at the University of Oxford.

**Comment by blackCmd** [comment]
@xksteven  how can i download?

**Comment by xksteven** [comment]
@blackCmd

Just use 

wget -r --no-parent --reject "index.html*" http://vision.cs.utexas.edu/voc/ 

I believe that website only has the 2007 dataset though. Let me know of you need finding the 2012 one. 

Also there is the fast-rcnn available in case you weren't aware.

**Comment by blackCmd** [comment]
@xksteven  oh, Thank you : )
i have another question.
Does The resource in http://vision.cs.utexas.edu/voc/ include VOCtrainval_06-Nov-2007.tar, VOCtest_06-Nov-2007.tar and VOCdevkit_08-Jun-2007.tar ?

**Comment by CyrusChiu** [comment]
@JoeHowse , thank you
this worked for me
```
wget http://host.robots.ox.ac.uk/pascal/VOC/voc2007/VOCtrainval_06-Nov-2007.tar
wget http://host.robots.ox.ac.uk/pascal/VOC/voc2007/VOCtest_06-Nov-2007.tar
wget http://host.robots.ox.ac.uk/pascal/VOC/voc2007/VOCdevkit_08-Jun-2007.tar
```
```
tar xvf VOCtrainval_06-Nov-2007.tar
tar xvf VOCtest_06-Nov-2007.tar
tar xvf VOCdevkit_08-Jun-2007.tar
```

**Comment by xksteven** [comment]
@blackCmd To answer your question they do have all of them but I would go with CyrusChiu response.  Those are the official ones anyways.  Sometimes the website goes down because the competition is over so the people who maintain the website might not notice and need a heads up.

This issue should be closed though at this point.

**Comment by pjreddie** [comment]
If anyone hits this issue and needs another mirror, I mirror the dataset on my website: http://pjreddie.com/projects/pascal-voc-dataset-mirror/

**Comment by ieee8023** [comment]
You can find these datasets on Academic Torrents:

http://academictorrents.com/browse.php?search=voc

**Comment by guanfuchen** [comment]
The url is not working, I download the dataset from [kaggle voc](https://www.kaggle.com/zaraks/pascal-voc-2007/version/1)

**Comment by felixnie** [comment]
Just change them to:
wget http://pjreddie.com/media/files/VOCtrainval_06-Nov-2007.tar
wget http://pjreddie.com/media/files/VOCtest_06-Nov-2007.tar
wget http://pjreddie.com/media/files/VOCdevkit_08-Jun-2007.tar

**Comment by abdelazizmirasoft** [comment]
Is there any Pascal VOC Dataset for hands detetctions?
